relays:
  1:
    name: Relay 1 - Battery
    pin: 12
  2:
    name: Relay 2 - Battery
    pin: 13
  3:
    name: Relay 3 - Precharge Battery
    pin: 20
  4:
    name: Relay 4 - Solar 1
    pin: 19
  5:
    name: Relay 5 - Solar 2
    pin: 24
kill_switch:
  pin: 16
