relays:
  1:
    name: Relay 1 - Battery
    pin: 5
  2:
    name: Relay 2 - Battery
    pin: 13
  3:
    name: Relay 3 - Precharge Battery
    pin: 17
  4:
    name: Relay 4 - Solar 1
    pin: 18
  5:
    name: Relay 5 - Solar 2
    pin: 12
  6:
    name: Relay 6
    pin: 6
kill_switch:
  pin: 16
